# Подсказка: Опция -I в gcc помогает решить проблему с поиском заголовочных файлов. (#include "" No such file or directory)
# Собрать многофайловый проект
# Для использования make его необходимо установить: sudo apt install make
targets:
	gcc -I ./pipes pipes/read_pipe.c pipes/write_pipe.c app/main.c -I ./background background/background.c